### ISSUE TITLE
SSL Confirmation

### ISSUE THREAD

**Issue by falloutphil** [dequis/bitlbee-ssl#1]
Hi,

A probably obvious question rather than an issue.

This plugin allows an account connection from Bitlbee gateway out to an IRC Chat Server using SSL.

This plugin does not allow a connection from an IRC Client (eg WeeChat) into the Bitlbee gateway to use SSL.

Is that correct?

**Comment by dequis** [comment]
Correct. This project is a joke honestly, but also happens to work as minimal boilerplate to develop other plugins.

You'll want something like stunnel.
